// <auto-generated>
// This file is generated by bin/generate-version from package.json.
// Do not edit manually.
// </auto-generated>

namespace PostHog
{
    static partial class SdkInfo
    {
        /// <summary>
        /// The current SDK version.
        /// </summary>
        public const string Version = "0.1.0";
    }
}
