on:
    push:
        branches:
            - main
    pull_request:
    merge_group:

name: Security

env:
    SEMGREP_ENABLE_VERSION_CHECK: 'false'

jobs:
    semgrep:
        runs-on: ubuntu-latest
        container:
            image: semgrep/semgrep:1.163.0@sha256:7cad2bc2d1e44f87f0bf4be6d1fa23aa90fb72015bebc89fb91385d813987a03

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Run Semgrep
              run: |
                  semgrep \
                    --config "p/owasp-top-ten" \
                    --config "p/security-audit" \
                    --config "p/trailofbits" \
                    --config "p/github-actions" \
                    --error \
                    --metrics=off \
                    .
