on:
    push:
        branches:
            - main
    pull_request:
    merge_group:

name: Security

env:
    SEMGREP_ENABLE_VERSION_CHECK: 'false'

jobs:
    semgrep:
        runs-on: ubuntu-latest
        container:
            image: semgrep/semgrep:1.163.0@sha256:7cad2bc2d1e44f87f0bf4be6d1fa23aa90fb72015bebc89fb91385d813987a03

        steps:
            - name: Checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Run Semgrep
              run: |
                  semgrep \
                    --config "p/owasp-top-ten" \
                    --config "p/security-audit" \
                    --config "p/trailofbits" \
                    --config "p/github-actions" \
                    --error \
                    --metrics=off \
                    .
